name: mechkonnect_auto_service_hub
description: "MechKonnect Auto Service Hub - A comprehensive automotive services platform connecting vehicle owners with trusted mechanics and service providers."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Routing
  go_router: ^12.1.3

  # Supabase Integration
  supabase_flutter: ^2.0.0

  # UI and Material Design
  material_color_utilities: ^0.8.0
  dynamic_color: ^1.6.8

  # Maps and Location
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  geolocator: ^10.1.0
  geocoding: ^2.1.1

  # HTTP and Networking
  http: ^1.1.2
  dio: ^5.4.0

  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Image Handling
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0

  # Utilities
  intl: ^0.19.0
  uuid: ^4.2.1
  url_launcher: ^6.2.2
  permission_handler: ^11.2.0

  # Authentication & Security
  crypto: ^3.0.3

  # Development
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^3.0.1

  # Code Generation
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  hive_generator: ^2.0.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

# Flutter configuration
flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  # Fonts
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

# Flutter launcher icons configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21

# Application metadata
flutter:
  generate: true